algoritmo "semnome"
// Função :
// Autor :
// Data : 11/03/2020
// Seção de Declarações 
var
pu,quant,porc,result:real
inicio
// Seção de Comandos 
//inicio
escreval("Qual o valor da peça?:")
leia(pu)
escreval("qual a quantidade vendida?:")
leia(quant)
escreval("qual a porcentagem?:")
leia(porc)

//processamento
result<-(pu*quant*0.05)

//saida
escreval("o valor valor da comissão é:",result)
fimalgoritmo
