algoritmo "semnome"
// Função :
// Autor :Caio Victor
// Data : 19/05/2020
// Seção de Declarações 
var
percurso,tempo,resp:real
inicio
// Seção de Comandos
//inicio
escreval("Qual foi o percurso percorrido:")
leia(percurso)
escreval("Qual o tempo gasto nesse percurso (em decimal):")
leia(tempo)

//processamento
resp<- (percurso/tempo)

//saida
escreval("voce percorreu:",resp)

fimalgoritmo
